version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    target-branch: "main"
    rebase-strategy: "auto"
    assignees:
      - "alihaidar0"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
    groups:
      github-actions-all:
        patterns:
          - "*"
    open-pull-requests-limit: 5

  - package-ecosystem: "docker"
    directory: "/docker"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    target-branch: "main"
    rebase-strategy: "auto"
    assignees:
      - "alihaidar0"
    commit-message:
      prefix: "build"
      include: "scope"
    labels:
      - "dependencies"
      - "docker"
    ignore:
      - dependency-name: "node"
        update-types:
          - "version-update:semver-patch"
          - "version-update:semver-minor"
          - "version-update:semver-major"
    open-pull-requests-limit: 3